<?php
// app/Core/Database.php

namespace App\Core;

use mysqli;

// Database configuration
// *** UPDATED TO USE RAILWAY'S MYSQL ENV VARS ***
// These names match the environment variables auto-generated by Railway's MySQL service
define('DB_HOST', 'sql305.infinityfree.com');
define('DB_USER', 'if0_40627650');
define('DB_PASS', 'zDm97qyXmb');
define('DB_NAME', 'lumora_db');
define('DB_PORT', 3306); // Added port variable

class Database {
    private static $conn;

    /**
     * Establishes and returns the database connection.
     */
    public static function getConnection() {
        if (!self::$conn) {
            // *** UPDATED TO INCLUDE DB_PORT AS THE FIFTH ARGUMENT ***
            error_log("DB_HOST: " . DB_HOST . " | DB_PORT: " . DB_PORT . " | DB_USER: " . DB_USER);
            $conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME, DB_PORT);

            if ($conn->connect_error) {
                error_log('Database connection failed: ' . $conn->connect_error);
                die('Database connection failed. Please try again later.');
            }
            
            $conn->set_charset('utf8mb4');
            self::$conn = $conn;
        }
        return self::$conn;
    }
}

// Initialize connection immediately
Database::getConnection();